name: gravitron

on: [push]

env:
  IMAGE_NAME: gravitron         # Replace with your desired image name
  ACR_NAME: multiarchtest      # Replace with your Azure Container Registry name

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven dependencies
        id: cache-maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn clean package

      - name: Save Maven dependencies cache
        if: steps.cache-maven.outputs.cache-hit == 'false'
        run: |
          mkdir -p ~/.m2
          mv ~/.m2/repository $GITHUB_WORKSPACE/m2-cache

      - name: Upload Maven dependencies cache
        if: steps.cache-maven.outputs.cache-hit == 'false'
        uses: actions/upload-artifact@v2
        with:
          name: m2-cache
          path: $GITHUB_WORKSPACE/m2-cache

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:latest
