name: gravitron

  #on:
  # Trigger the workflow on push or pull request,
# but only for the development branch
#  push:
#    branches:
#      - development
# it will create a release branch if it is triggered via scheduler
on: [push]

env:
  IMAGE_NAME: gravitron  # Replace with your desired image name
  ACR_NAME: multiarchtest      # Replace with your Azure Container Registry name

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:latest